// apps/MishraShardendu22-Frontend-BlogWebsite/src/components/blog/ThemeToggle.tsx
import { Moon, Sun } from 'lucide-react'
import { useEffect, useState } from 'react'

export default function ThemeToggle() {
  const [theme, setTheme] = useState<'light' | 'dark'>('light')
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    // Get theme from localStorage or system preference
    const storedTheme = localStorage.getItem('theme')
    const systemTheme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
    const initialTheme = storedTheme as 'light' | 'dark' || systemTheme
    
    setTheme(initialTheme)
    document.documentElement.classList.toggle('dark', initialTheme === 'dark')
  }, [])

  const toggleTheme = () => {
    const newTheme = theme === 'dark' ? 'light' : 'dark'
    setTheme(newTheme)
    localStorage.setItem('theme', newTheme)
    document.documentElement.classList.toggle('dark', newTheme === 'dark')
  }

  if (!mounted) {
    return <div className="w-10 h-10" /> // Placeholder to prevent layout shift
  }

  return (
    <button
      onClick={toggleTheme}
      className="relative rounded-full w-10 h-10 bg-card border border-border hover:bg-accent hover:text-accent-foreground transition-colors flex items-center justify-center"
      aria-label="Toggle theme"
    >
      <Sun className="h-5 w-5 rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
      <Moon className="absolute h-5 w-5 rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
      <span className="sr-only">Toggle theme</span>
    </button>
  )
}

// apps/MishraShardendu22-Frontend-BlogWebsite/src/lib/components/ThemeToggle.svelte
<script lang="ts">
  import { Moon, Sun } from "lucide-svelte";
  import { themeStore } from "../theme";
  import { onMount } from "svelte";

  let theme = $state<"light" | "dark">("light");
  let mounted = $state(false);

  onMount(() => {
    // Initialize theme
    themeStore.init();
    mounted = true;
  });

  // Subscribe to theme changes
  themeStore.subscribe((t) => {
    theme = t;
  });

  function toggleTheme() {
    themeStore.toggle();
  }
</script>

{#if mounted}
  <button
    aria-label="Toggle Dark Mode"
    class="fixed bottom-6 right-6 z-50 p-3 rounded-full bg-card shadow-lg border border-border hover:bg-accent hover:border-accent-foreground transition-all duration-200 hover:scale-110"
    onclick={toggleTheme}
  >
    {#if theme === "dark"}
      <Sun class="w-5 h-5 text-yellow-400 transition-transform duration-300" />
    {:else}
      <Moon class="w-5 h-5 text-foreground transition-transform duration-300" />
    {/if}
  </button>
{/if}

<style>
  button {
    box-shadow: 0 4px 6px -1px var(--shadow), 0 2px 4px -1px var(--shadow);
  }

  button:hover {
    box-shadow: 0 10px 15px -3px var(--shadow-strong),
      0 4px 6px -2px var(--shadow);
  }

  button:active {
    transform: scale(0.95);
  }
</style>
