// apps/MishraShardendu22-Frontend-BlogWebsite/src/lib/components/ui/input.svelte
<script lang="ts">
  import { cn } from "../../utils";

  let {
    class: className,
    type = "text",
    value = $bindable(),
    ...restProps
  }: {
    class?: string;
    type?: string;
    value?: string;
    [key: string]: any;
  } = $props();
</script>

<input
  {type}
  bind:value
  class={cn(
    "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-base ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
    className
  )}
  {...restProps}
/>

// apps/MishraShardendu22-Frontend-AdminWebsite/src/components/ui/input.tsx
import { forwardRef } from 'preact/compat'
import { cn } from '../../lib/utils'
import type { JSX } from 'preact'

export interface InputProps extends JSX.HTMLAttributes<HTMLInputElement> {
  type?: string
  disabled?: boolean
  value?: string | number
  onChange?: JSX.GenericEventHandler<HTMLInputElement>
  required?: boolean
  placeholder?: string
}

const Input = forwardRef<HTMLInputElement, InputProps>(
  ({ className, type = 'text', disabled, ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(
          'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
          className
        )}
        ref={ref}
        disabled={disabled}
        {...props}
      />
    )
  }
)

Input.displayName = 'Input'

export { Input }
