// apps/MishraShardendu22-Frontend-BlogWebsite/src/components/ui/avatar.tsx
import * as React from 'react'
import * as AvatarPrimitive from '@radix-ui/react-avatar'

import { cn } from '@/lib/utils'

const Avatar = React.forwardRef<
  React.ElementRef<typeof AvatarPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof AvatarPrimitive.Root>
>(({ className, ...props }, ref) => (
  <AvatarPrimitive.Root
    ref={ref}
    className={cn('relative flex size-10 shrink-0 overflow-hidden rounded-full', className)}
    {...props}
  />
))
Avatar.displayName = AvatarPrimitive.Root.displayName

const AvatarImage = React.forwardRef<
  React.ElementRef<typeof AvatarPrimitive.Image>,
  React.ComponentPropsWithoutRef<typeof AvatarPrimitive.Image>
>(({ className, ...props }, ref) => (
  <AvatarPrimitive.Image
    ref={ref}
    className={cn('aspect-square size-full', className)}
    {...props}
  />
))
AvatarImage.displayName = AvatarPrimitive.Image.displayName

const AvatarFallback = React.forwardRef<
  React.ElementRef<typeof AvatarPrimitive.Fallback>,
  React.ComponentPropsWithoutRef<typeof AvatarPrimitive.Fallback>
>(({ className, ...props }, ref) => (
  <AvatarPrimitive.Fallback
    ref={ref}
    className={cn(
      'flex size-full items-center justify-center rounded-full bg-muted',
      className
    )}
    {...props}
  />
))
AvatarFallback.displayName = AvatarPrimitive.Fallback.displayName

export { Avatar, AvatarImage, AvatarFallback }

// apps/MishraShardendu22-Frontend-BlogWebsite/src/lib/components/ui/avatar.svelte
<script lang="ts">
  import { cn } from "../../utils";

  let {
    class: className,
    src,
    alt = "",
    fallback,
    ...restProps
  }: {
    class?: string;
    src?: string;
    alt?: string;
    fallback?: string;
    [key: string]: any;
  } = $props();

  let imageLoaded = $state(false);
  let imageError = $state(false);
</script>

<div
  class={cn("relative flex h-10 w-10 shrink-0 overflow-hidden rounded-full", className)}
  {...restProps}
>
  {#if src && !imageError}
    <img
      {src}
      {alt}
      class={cn("aspect-square h-full w-full object-cover", imageLoaded ? "opacity-100" : "opacity-0")}
      onload={() => (imageLoaded = true)}
      onerror={() => (imageError = true)}
    />
  {/if}
  {#if !src || imageError || !imageLoaded}
    <div class="flex h-full w-full items-center justify-center rounded-full bg-muted text-sm">
      {fallback || ""}
    </div>
  {/if}
</div>
