// apps/MishraShardendu22-Frontend-AdminWebsite/src/components/ui/label.tsx
import { forwardRef } from 'preact/compat'
import { cn } from '../../lib/utils'
import type { JSX } from 'preact'

export interface LabelProps extends JSX.HTMLAttributes<HTMLLabelElement> {
  htmlFor?: string
}

const Label = forwardRef<HTMLLabelElement, LabelProps>(({ className, ...props }, ref) => {
  return (
    <label
      ref={ref}
      className={cn(
        'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
        className
      )}
      {...props}
    />
  )
})

Label.displayName = 'Label'

export { Label }

// apps/MishraShardendu22-Frontend-BlogWebsite/src/lib/components/ui/label.svelte
<script lang="ts">
  import { cn } from "../../utils";

  let {
    class: className,
    children,
    ...restProps
  }: {
    class?: string;
    children?: any;
    [key: string]: any;
  } = $props();
</script>

<label
  class={cn(
    "text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
    className
  )}
  {...restProps}
>
  {@render children?.()}
</label>
